name: Build

on:
  workflow_dispatch:
#   push:
#     branches: [main]
#     paths-ignore:
#       - "**.md"
#       - "**.spec.js"
#       - ".idea"
#       - ".vscode"
#       - ".dockerignore"
#       - "Dockerfile"
#       - ".gitignore"
#       - ".github/**"
#       - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1
      - name: node version
        run: node -v
      - name: Install-Yarn
        run: npm install -g yarn
      - name: Yarn-version
        run: yarn -v
      - name: Install Dependencies
        run: yarn install

      - name: Build Release Files
        run: yarn run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: app
        run: yarn run build:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: release_on_${{ matrix. os }}
#           path: release/
#           retention-days: 5
